info:
  app:
    name: Infracheck Example
    description: Example application that uses infracheck
    version: 1.0-SNAPSHOT
management:
  security:
    enabled: false
server:
  port: 8080

apicem:
  traceId: 83146cfe-44f1-4445-94e7-87c6327490c8
  username: devnetuser
  password: Cisco123!
  url: https://sandboxapicem.cisco.com/api