info:
  app:
    name: Infracheck Example
    description: Example application that uses infracheck
    version: 1.0-SNAPSHOT
management:
  security:
    enabled: false
server:
  port: 8080

apicem:
  traceId: 3772b101-6769-4dd7-9fbf-cdd45d8971ea