info:
  app:
    name: Infracheck Example
    description: Example application that uses infracheck
    version: 1.0-SNAPSHOT
management:
  security:
    enabled: false
server:
  port: 8080

controller:
  traceId: 760b0560-1da2-42dc-8bc3-5d7a48a71150
  username: admin
  password: Cisco123
  url: https://192.168.139.73/api